version: '3.8'
services:
  db:
    image: postgres:12.1
    environment:
      POSTGRES_USER: eatery
    ports:
      - '5432:5432'
    volumes:
      - ./db/scripts/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - eatery-db:/var/lib/postgresql/data
    restart: always

volumes:
  eatery-db:
